### ISSUE TITLE
Naïve Bayes linker experiment

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#146]
This is the first step towards the probabilistic linker.
Workflow: clean, index (AKA block), compare, classify, evaluate.
- [x] _recordlinkage_ library, #137;
- [x] Wikidata: slice the relevant subset out of the dump, via SPARQL or #138;
- [x] target: query our DB for the set of entities;
- [x] clean, either via `commons/text_utils.py` and `commons/url_utils.py` or #140;
- [x] index/block via `commons/candidate_acquisition.py` or #141;
- [x] compare, #142;
- [x] build training set: SPARQL query Wikidata with `python -m soweego wikidata class_based_identifier_query CLASS_QID CATALOG_PID`;
- [x] features, #143;
- [x] classify, #144;
- [x] evaluate, #145.

**Comment by marfox** [comment]
> - [ ] build training set: SPARQL query Wikidata with `python -m soweego wikidata class_based_identifier_query CLASS_QID CATALOG_PID`;

This is not enough, we also need to:
- [ ] get the Wikidata relevant statements;
- [ ] get the corresponding target data.

See https://github.com/Wikidata/soweego/wiki/Notes-on-the-recordlinkage-Python-library#training-workflow
