### ISSUE TITLE
Training with negative samples 

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#186]
#### Input
1. Wikidata training DataFrame, output of `workflow#build_wikidata('training', ...);
2. target training DataFrame, output of `workflow#build_target('training', ...);
3. target classification DataFrame, output of `workflow#build_target('classification', ...)`.

#### Tasks
- [x] block 1 and 2 on target IDs = index of positive samples: `workflow#train_test_block = positive_index`;
- [x] block ~~1 and 3~~ via full-text query on names = ~~index of negative samples:~~ #178 = ~~`negative_index`~~; queries actually retrieve **both** positive and negative samples, so `samples_index`;
- [x] slice positive samples from `samples_index`;
- [x] ~~extract features over index of _positive_ samples;~~
- [x] ~~extract features over index of _negative_ samples;~~
- [x] extract features over `samples_index`;
- [x] ~~concatenate positive and negative feature vector DataFrames = `feature_vectors`;~~ not needed anymore
- [x] fit classifier: `train#_train('nb', feature_vectors, positive_index, 0.1)`.
