### ISSUE TITLE
Try SVC with linear kernel instead of LinearSVC

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#269]
`recordlinkage` uses scikit's [LinearSVC](https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html) as its SVM classifier.
However, it doesn't output probability scores.

- [x] Try [SVC](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html) with a linear kernel;
- [x] inject it into `recordlinkage`;
- [x] make sure to output probability scores with the `prob` method;
- [x] add report to ~~#204~~ https://github.com/Wikidata/soweego/wiki/Linkers-evaluation.
- [x] ~~add report to #203;~~
- [x] ~~add report to #171.~~
