### ISSUE TITLE
Super-confident predictions

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#305]
Different classifiers may capture different relations in the data. We can join what each classifier learns by creating ensembles of them. 

- [x] Use sklearn's VotingClassifier instead of our implementation - #366 
- [x] Implement a Gating ensemble - #356 
- [x] Implement a Stacking ensemble - #367 

Results will then be presented in a separate task

- [x]  Analyze performance of ensemble methods - #359

**Comment by tupini07** [comment]
It seems that ensembles are commonly used in RL pipelines to predict if 2 entities match or not. Ensembles are usually composed of diverse models (eg, SVM + Decision Trees). A couple of examples: 

In [1] a final ensemble is used to _self learn_ on a partially labelled dataset. In [2] they use multiple classifiers to predict a match, the final classifier is selected depending on its score and how interpretable the model is.

1. [A novel ensemble learning approach to unsupervised record linkage (2017)](https://www.sciencedirect.com/science/article/abs/pii/S0306437916305063)
2. [Magellan: Toward Building Entity Matching Management Systems (2016)](https://www.semanticscholar.org/paper/Magellan%3A-Toward-Building-Entity-Matching-Systems-Konda-Das/097131e143563798078e8c9b7447fb1c77eb34ec)
