### ISSUE TITLE
Radical uplift epic

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#436]
- [ ] Replace Docker with Conda
- [ ] bump Python to latest version
- [ ] bump as many dependencies as possible to their latest version
- [ ] backup the current Cloud VPS instance
- [ ] delete it
- [ ] spawn a fresh one with the latest OS
- [ ] update docs

**Comment by marfox** [comment]
Debian 11 bullseye on

**Comment by marfox** [comment]
Debian 11 bullseye on
